/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessageRelay } from "./MessageRelay";
export * as factories from "./factories";
export { MessageRelay__factory } from "./factories/MessageRelay__factory";
